@tool
class_name QuickExportSettings
extends Node
## Editor helper for configuring existing export presets. [br]
## Add this script to a Node, press the desired buttons, then remove the Node.


#region export paths


@export_group("Export paths")


## Root folder used for every build
@export_global_dir var builds_root: String = _get_default_builds_root()


## Reset the builds root to the current user's Documents/Builds folder
@export_tool_button("Reset path to Documents/Builds")
var reset_builds_root: Callable = _reset_builds_root


func _get_default_builds_root() -> String:
	# get Documents folder in your pc
	var documents_path: String = OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)
	if documents_path.is_empty():
		return ""
	# and return path/to/Documents/Builds
	return documents_path.path_join("Builds")


func _reset_builds_root() -> void:
	# reset path to Documents/Builds folder, and update variable in inspector
	builds_root = _get_default_builds_root()
	notify_property_list_changed()
	_success_message(str("Builds root reset to '", builds_root, "'"))


#endregion


#region project settings for export builds


@export_group("Project Settings for export builds")


## Set texture compression for build android
@export_tool_button("Set texture compression for android")
var settings_for_android: Callable = _settings_for_android


const TEXTURE_COMPRESSION_SETTING: String = "rendering/textures/vram_compression/import_etc2_astc"


func _settings_for_android() -> void:
	# update settings for android
	var setting: bool = ProjectSettings.get_setting(TEXTURE_COMPRESSION_SETTING, false)
	if setting == false:
		ProjectSettings.set_setting(TEXTURE_COMPRESSION_SETTING, true)
		_save_project_settings("Edited settings for Android build")
	# if not already set
	else:
		_warning_message("Settings are already ready for Android build")


#endregion


#region configure presets


@export_group("Configure presets")


## Path to the export_presets.cfg generated by godot when add exports to the project
@export_file var export_presets_path: String = "res://export_presets.cfg"


## Configure every supported export presets
@export_tool_button("Configure all export presets")
var configure_all_presets: Callable = _configure_all_presets


## Configure only Android presets
@export_tool_button("Configure Android presets")
var configure_android_presets: Callable = _configure_android_presets


## Configure only Linux presets
@export_tool_button("Configure Linux presets")
var configure_linux_presets: Callable = _configure_linux_presets


## Configure only Windows presets
@export_tool_button("Configure Windows presets")
var configure_windows_presets: Callable = _configure_windows_presets


## Configure only WebGL presets
@export_tool_button("Configure WebGL presets")
var configure_webgl_presets: Callable = _configure_webgl_presets


# how are declared presets inside the file
const PRESET_SECTION_PREFIX: String = "preset."		# preset.0, preset.1, etc...
const OPTIONS_SECTION_SUFFIX: String = ".options"	# preset.0.options, preset.1.options, etc...

# possible devices
const DEVICE_ANDROID: String = "Android"
const DEVICE_LINUX: String = "Linux"
const DEVICE_WINDOWS: String = "Windows"
const DEVICE_WEBGL: String = "WebGL"

# necessary options
const PLATFORM_KEY: String = "platform"
const ANDROID_FORMAT_KEY: String = "gradle_build/export_format"

# options to set
const EXPORT_PATH_KEY: String = "export_path" # for every device
const EMBED_PCK_KEY: String = "binary_format/embed_pck" # for linux and windows
const WEB_MOBILE_COMPRESSION_KEY: String = "vram_texture_compression/for_mobile" # for webgl


func _configure_all_presets() -> void:
	_configure_presets(PackedStringArray([
		DEVICE_ANDROID,
		DEVICE_LINUX,
		DEVICE_WINDOWS,
		DEVICE_WEBGL,
	]))


func _configure_android_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_ANDROID]))


func _configure_linux_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_LINUX]))


func _configure_windows_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_WINDOWS]))


func _configure_webgl_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_WEBGL]))



func _configure_presets(requested_devices: PackedStringArray) -> void:
	# load export_presets.cfg file
	var export_settings: ConfigFile = _load_export_settings()
	if not export_settings:
		return 

	var changed: bool = false
	var matched_devices := PackedStringArray()
	var preset_index: int = 0

	# cycle every preset (they are named preset.0, preset.1, etc...)
	while true:
		var preset_section: String = PRESET_SECTION_PREFIX + str(preset_index)
		if not export_settings.has_section(preset_section):
			break

		# check if this is a requested device to edit
		var platform: String = str(export_settings.get_value(preset_section, PLATFORM_KEY, ""))
		var device: String = _get_device_from_platform(platform)
		if requested_devices.has(device):
			matched_devices.append(device)
			# and try edit it
			changed = _configure_preset(export_settings, preset_section, device) or changed

		preset_index += 1

	# warning for every device not found
	for device: String in requested_devices:
		if not matched_devices.has(device):
			_warning_message(str("No ", device, " export preset found"))

	# if nothing changed, warning
	if not changed:
		_warning_message("Export presets are already configured")
		return

	# save file if edited
	_save_export_settings(export_settings)


# configure single preset
# config is export_presets file, 
# preset_section is preset.0, preset.1, etc...
# device is Android, Linux, etc...
func _configure_preset(config: ConfigFile, preset_section: String, device: String) -> bool:
	# get options (they are named preset.0.options, preset.1.options, etc...)
	var options_section: String = preset_section + OPTIONS_SECTION_SUFFIX

	# get export path
	var export_path: String = _get_export_path(config, options_section, device)

	# create folders if not exist
	var export_directory: String = export_path.get_base_dir()
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(export_directory)
	if directory_error != OK and directory_error != ERR_ALREADY_EXISTS:
		_error_message(str("Cannot create '", export_directory, "': "), directory_error)
		return false

	# and set export path
	var changed: bool = _set_value_if_different(config, preset_section, EXPORT_PATH_KEY, export_path)

	# and set specific device options
	match device:
		DEVICE_LINUX, DEVICE_WINDOWS:
			changed = _set_value_if_different(config, options_section, EMBED_PCK_KEY, true) or changed
		DEVICE_WEBGL:
			changed = _set_value_if_different(config, options_section, WEB_MOBILE_COMPRESSION_KEY, true) or changed

	return changed


func _get_device_from_platform(platform: String) -> String:
	# from options platform, return readable device
	match platform:
		"Android":
			return DEVICE_ANDROID
		"Linux", "Linux/BSD", "Linux/X11":
			return DEVICE_LINUX
		"Windows", "Windows Desktop":
			return DEVICE_WINDOWS
		"Web", "WebGL", "HTML5":
			return DEVICE_WEBGL
		_:
			return ""


# return path/to/Documents/Builds/device/project_name/file_name.extension
func _get_export_path(config: ConfigFile, options_section: String, device: String) -> String:
	var project_name: String = _get_project_name()

	# get "path/to/Documents/Builds/device/project_name" 
	# where device is Android, Linux, etc...
	if builds_root.is_empty():
		_reset_builds_root()
	var export_directory: String = builds_root.simplify_path().path_join(device).path_join(project_name)
	var file_name: String

	# get file_name.extension
	match device:
		DEVICE_ANDROID:
			var android_format: int = int(config.get_value(options_section, ANDROID_FORMAT_KEY, 0))
			file_name = project_name + (".aab" if android_format == 1 else ".apk")
		DEVICE_LINUX:
			file_name = project_name + ".x86_64"
		DEVICE_WINDOWS:
			file_name = project_name + ".exe"
		DEVICE_WEBGL:
			file_name = "index.html"
		_:
			file_name = project_name

	return export_directory.path_join(file_name)


func _set_value_if_different(config: ConfigFile, section: String, key: String, value: Variant) -> bool:
	# ignore if already correct
	if config.has_section_key(section, key) and config.get_value(section, key) == value:
		return false
	# or set it
	config.set_value(section, key, value)
	return true


#endregion


#region Android release keystore


@export_group("Android release keystore")


## Complete path of the keystore that will be generated
@export_global_file var android_keystore_path: String = ""


## Set the keystore path to res://ProjectName.keystore
@export_tool_button("Set path to project root")
var set_keystore_to_project_root: Callable = _set_keystore_to_project_root



@export_subgroup("Safe creation")


## For a Safe Creation, create a file .txt with format: [keystore] \n alias="alias_value" \n password="password_value" [br]
## instead of write them in inspector
@export_global_file var  safe_keystore_credentials_path: String = ""


## Read alias and password from keystore_credentials.txt
@export_tool_button("Create keystore - Safe")
var create_keystore_safe: Callable = _create_keystore_safe


# options inside credentials file
const KEYSTORE_CREDENTIALS_SECTION: String = "keystore"
const KEYSTORE_ALIAS_KEY: String = "alias"
const KEYSTORE_PASSWORD_KEY: String = "password"
 


@export_subgroup("Fast creation")


## Alias used only by Fast creation
@export var fast_keystore_alias: String = ""


## Password used only by Fast creation
@export var fast_keystore_password: String = ""


## Create the keystore using credentials written in the Inspector
@export_tool_button("Create keystore - Fast")
var create_keystore_fast: Callable = _create_keystore_fast



const START_PROJECT_PATH: String = "res://"

# options inside export settings
const ANDROID_RELEASE_KEYSTORE_PATH_KEY: String = "keystore/release"
const ANDROID_RELEASE_ALIAS_KEY: String = "keystore/release_user"
const ANDROID_RELEASE_PASSWORD_KEY: String = "keystore/release_password"

# generate also export_credentials.cfg
const EXPORT_CREDENTIALS_PATH: String = "res://.godot/export_credentials.cfg"


func _set_keystore_to_project_root() -> void:
	# reset android_keystore_path to project path, and update variable in inspectpr
	var project_name: String = _get_project_name()
	android_keystore_path = START_PROJECT_PATH + project_name + ".keystore"
	notify_property_list_changed()
	_success_message(str("Android keystore path set to '", android_keystore_path, "'"))


func _get_global_path(current_path: String) -> String:
	# trim current path
	current_path = current_path.strip_edges()
	if current_path.is_empty():
		return ""
	# if local to project, return absolute path
	return ProjectSettings.globalize_path(current_path).simplify_path()


## Read alias and password from keystore_credentials.txt
func _create_keystore_safe() -> void:
	# get keystore and credentials path
	var keystore_path: String = _get_global_path(android_keystore_path)
	if keystore_path.is_empty():
		_error_message_only("Android keystore path is empty")
		return

	var credentials_path: String = _get_global_path(safe_keystore_credentials_path)
	if credentials_path.is_empty():
		_error_message_only("Android Safe Keystore Credentials path is empty")
		return

	# try load credentials
	var credentials := ConfigFile.new()
	var load_error: Error = credentials.load(credentials_path)
	if load_error == ERR_FILE_NOT_FOUND:
		_error_message_only(str("No credentials file found at '", credentials_path, "'. 
			Expected format: [keystore] \n alias=\"alias_value\" \n password=\"password_value\""))
		return

	if load_error != OK:
		_error_message("Cannot load credentials file: ", load_error)
		return

	# get alias and password
	var alias: String = str(credentials.get_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_ALIAS_KEY, "")).strip_edges()
	var password: String = str(credentials.get_value(KEYSTORE_CREDENTIALS_SECTION, KEYSTORE_PASSWORD_KEY, ""))

	if alias.is_empty() or password.is_empty():
		_error_message_only("The credentials file must contain a valid alias and password")
		return

	# generate keystore and edit export settings to use it
	if _generate_android_keystore(keystore_path, alias, password):
		_configure_android_release_credentials(keystore_path, alias, password)

		# warn if keystore or credentials are inside project folder
		_warn_if_path_is_inside_project(keystore_path, "The release keystore")
		_warn_if_path_is_inside_project(credentials_path, "The credentials file")


## Create the keystore using credentials written in the Inspector
func _create_keystore_fast() -> void:
	_warning_message(
		"Fast creation should only be used for debug or testing. 
		Alias and password entered in the Inspector could be saved inside the scene and pushed to the repository. 
		Use 'Create keystore - Safe' for a real release keystore."
	)

	# get keystore
	var keystore_path: String = _get_global_path(android_keystore_path)
	if keystore_path.is_empty():
		_error_message_only("Android keystore path is empty")
		return

	# get alias and password from variables in inspector
	var alias: String = fast_keystore_alias.strip_edges()
	var password: String = fast_keystore_password

	if alias.is_empty():
		_error_message_only("Fast keystore alias is empty")
		return

	if password.is_empty():
		_error_message_only("Fast keystore password is empty")
		return

	if _generate_android_keystore(keystore_path, alias, password):
		_configure_android_release_credentials(keystore_path, alias, password)

		# Remove credentials from the exported Inspector properties.
		fast_keystore_alias = ""
		fast_keystore_password = ""
		notify_property_list_changed()

		# warn if keystore is inside project folder
		_warn_if_path_is_inside_project(keystore_path, "The release keystore")


## Execute [br]
## keytool -v -genkey -keystore mygame.keystore -alias mygame -keyalg RSA -validity 10000 [br]
## https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html
func _generate_android_keystore(keystore_path: String, alias: String, password: String) -> bool:
	if password.length() < 6:
		_error_message_only("The keystore password must contain at least 6 characters")
		return false

	if FileAccess.file_exists(keystore_path):
		_error_message_only(str("A file already exists at '", keystore_path,"'. It will not be overwritten."))
		return false

	# create directories
	var keystore_directory: String = keystore_path.get_base_dir()
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(keystore_directory)

	if directory_error != OK and directory_error != ERR_ALREADY_EXISTS:
		_error_message("Cannot create keystore keystore_directory: ", directory_error)
		return false

	# execute application to generate keystore
	var keytool_path: String = _get_keytool_path()
	var output: Array = []

	var arguments := PackedStringArray([
		"-v",
		"-genkey",
		"-keystore", keystore_path,
		"-alias", alias,
		"-keyalg", "RSA",
		# "-keysize", "2048",
		"-validity", "10000",
		# next arguments are used to set password, name, organizations, etc... without ask questions in console
		"-storepass", password,
		"-keypass", password,
		"-dname", "CN=Godot Release, O=Godot",
	])

	var exit_code: int = OS.execute(keytool_path, arguments, output, true)

	# check errors
	if exit_code != 0:
		_error_message_only(str("Cannot generate Android keystore. Exit code: ", exit_code, ". Output: ", "\n".join(output)))
		return false

	if not FileAccess.file_exists(keystore_path):
		_error_message_only("Keytool completed but the keystore was not generated")
		return false

	# else, success
	_success_message(str("Android release keystore generated at '", keystore_path, "'"))
	return true


## Find keytool -> java_sdk_folder/bin/keytool
func _get_keytool_path() -> String:
	var executable_name: String = ("keytool.exe" if OS.get_name() == "Windows" else "keytool")
	var java_sdk_path: String = str(EditorInterface.get_editor_settings().get_setting("export/android/java_sdk_path"))

	if not java_sdk_path.is_empty():
		# find keytool -> java_sdk_folder/bin/keytool
		var configured_path: String = java_sdk_path.path_join("bin").path_join(executable_name)

		if FileAccess.file_exists(configured_path):
			return configured_path

	# Fall back to the keytool available in PATH
	return executable_name


func _warn_if_path_is_inside_project(path: String, description: String) -> void:
	# check if path is inside project
	var global_path: String = ProjectSettings.globalize_path(path)
	var localized_path: String = ProjectSettings.localize_path(global_path)

	# if inside project, show a warning message
	if localized_path.begins_with(START_PROJECT_PATH):
		_warning_message(str(description, " is inside the project. Do not push it to the repository. Add it to .gitignore or, preferably, keep it outside the project."))


func _configure_android_release_credentials(keystore_path: String, alias: String, password: String) -> void:
	# load export_presets.cfg file
	# Used only to discover which presets are Android presets.
	var export_settings: ConfigFile = _load_export_settings()
	if not export_settings:
		return
	
	# Load Godot's existing credentials to avoid overwriting credentials belonging to other presets
	var export_credentials_config := ConfigFile.new()
	var credentials_error: Error = export_credentials_config.load(EXPORT_CREDENTIALS_PATH)

	if (credentials_error != OK and credentials_error != ERR_FILE_NOT_FOUND):
		_error_message("Cannot load export credentials: ", credentials_error)
		return

	var android_presets_found: int = 0
	var preset_index: int = 0

	# cycle every preset (they are named preset.0, preset.1, etc...)
	while true:
		var preset_section: String = PRESET_SECTION_PREFIX + str(preset_index)
		if not export_settings.has_section(preset_section):
			break		

		# check if this is an Android device to edit
		var platform: String = str(export_settings.get_value(preset_section, PLATFORM_KEY, ""))
		var device: String = _get_device_from_platform(platform)
		if device == DEVICE_ANDROID:

			# get options (they are named preset.0.options, preset.1.options, etc...)
			var options_section: String = preset_section + OPTIONS_SECTION_SUFFIX

			# set keystore, alias and password, inside export_credentials, but using export_preset found options_section
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_KEYSTORE_PATH_KEY, keystore_path)
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_ALIAS_KEY, alias)
			export_credentials_config.set_value(options_section, ANDROID_RELEASE_PASSWORD_KEY, password)

			android_presets_found += 1

		preset_index += 1

	if android_presets_found == 0:
		_warning_message("Keystore generated, but no Android export preset was found")
		return
	
	# now instead of save export_presets.cfg, we must generate a export_credentials.cfg

	# save export_credentials
	var credentials_directory: String = ProjectSettings.globalize_path(EXPORT_CREDENTIALS_PATH.get_base_dir())
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(credentials_directory)
	if (directory_error != OK and directory_error != ERR_ALREADY_EXISTS):
		_error_message("Cannot create export credentials directory: ", directory_error)
		return
	
	_save_export_credentials(export_credentials_config, android_presets_found)


#endregion


func _get_project_name() -> String:
	# get project name (if some chars are invalid, they are replaced with underscore _)
	var project_name: String = str(ProjectSettings.get_setting("application/config/name", "GodotProject"))
	project_name = project_name.strip_edges().validate_filename()
	if project_name.is_empty():
		project_name = "GodotProject"
	return project_name


func _save_project_settings(success_message: String) -> void:
	var save_error: Error = ProjectSettings.save()
	if save_error == OK:
		_success_message(success_message)
		push_warning("Project Settings saved! Reload the project to avoid cache bugs")
	else:
		_error_message("Cannot save Project Settings: ", save_error)


func _load_export_settings() -> ConfigFile:
	# load export_presets.cfg file
	var config := ConfigFile.new()
	var load_error: Error = config.load(export_presets_path)

	if load_error == ERR_FILE_NOT_FOUND:
		_error_message_only("No export_presets.cfg found. Create the export presets first. 
			In the top bar: Project > Export > Add > select device. 
			If necessary: Editor > Manage export models > download necessary models. 
			What I download: Windows x86_64 (no console), Linux x86_64, Android (no source), Web no threads. Both debug and release")
		return null

	if load_error != OK:
		_error_message("Cannot load export_presets.cfg: ", load_error)
		return null

	return config


func _save_export_settings(config: ConfigFile) -> void:
	# save file if edited
	var save_error: Error = config.save(export_presets_path)
	if save_error == OK:
		_success_message("Export presets configured")
		push_warning("Export presets saved! Reload the project so the Export window refreshes its cached presets")
	else:
		_error_message("Cannot save export_presets.cfg: ", save_error)


func _save_export_credentials(config: ConfigFile, android_presets_found: int) -> void:
	var save_error: Error = config.save(EXPORT_CREDENTIALS_PATH)
	if save_error == OK:
		_success_message(str("Android release credentials configured for ", android_presets_found, " preset(s)"))
		push_warning("Export credentials saved! Reload the project so the Export "+ "window refreshes its cached values")
	else:
		_error_message("Cannot save Android export credentials: ", save_error)



func _success_message(message: String) -> void:
	print("Quick Export Settings SUCCESS: ", message)


func _warning_message(message: String) -> void:
	push_warning("Quick Export Settings WARNING: ", message)


func _error_message(message: String, error: Error) -> void:
	push_error("Quick Export Settings ERROR: ", message, error_string(error))


func _error_message_only(message: String) -> void:
	push_error("Quick Export Settings ERROR: ", message)
