@tool
class_name QuickExportSettings
extends Node
## Editor helper for configuring existing export presets. [br]
## Add this script to a Node, press the desired buttons, then remove the Node.


#region export paths


@export_group("Export paths")


## Root folder used for every build
@export_global_dir var builds_root: String = _get_default_builds_root()


## Reset the builds root to the current user's Documents/Builds folder
@export_tool_button("Reset path to Documents/Builds")
var reset_builds_root: Callable = _reset_builds_root


func _get_default_builds_root() -> String:
	# get Documents folder in your pc
	var documents_path: String = OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS)
	if documents_path.is_empty():
		return ""
	# and return path/to/Documents/Builds
	return documents_path.path_join("Builds")


func _reset_builds_root() -> void:
	# reset path to Documents/Builds folder, and update variable in inspector
	builds_root = _get_default_builds_root()
	notify_property_list_changed()
	_success_message("Builds root reset to '", builds_root, "'")


#endregion


#region project settings for export builds


@export_group("Project Settings for export builds")


## Set texture compression for build android
@export_tool_button("Set texture compression for android")
var settings_for_android: Callable = _settings_for_android


const TEXTURE_COMPRESSION_SETTING: String = "rendering/textures/vram_compression/import_etc2_astc"


func _settings_for_android() -> void:
	# update settings for android
	var setting: bool = ProjectSettings.get_setting(TEXTURE_COMPRESSION_SETTING, false)
	if setting == false:
		ProjectSettings.set_setting(TEXTURE_COMPRESSION_SETTING, true)
		_save_project_settings("Edited settings for Android build")
	# if not already set
	else:
		_warning_message("Settings are already ready for Android build")


#endregion

#region configure presets


@export_group("Configure presets")


## Path to the export_presets.cfg generated by godot when add exports to the project
@export_file var export_presets_path: String = DEFAULT_EXPORT_PRESETS_PATH


## Configure every supported export presets
@export_tool_button("Configure all export presets")
var configure_all_presets: Callable = _configure_all_presets


## Configure only Android presets
@export_tool_button("Configure Android presets")
var configure_android_presets: Callable = _configure_android_presets


## Configure only Linux presets
@export_tool_button("Configure Linux presets")
var configure_linux_presets: Callable = _configure_linux_presets


## Configure only Windows presets
@export_tool_button("Configure Windows presets")
var configure_windows_presets: Callable = _configure_windows_presets


## Configure only WebGL presets
@export_tool_button("Configure WebGL presets")
var configure_webgl_presets: Callable = _configure_webgl_presets


const DEFAULT_EXPORT_PRESETS_PATH: String = "res://export_presets.cfg"

# how are declared presets inside the file
const PRESET_SECTION_PREFIX: String = "preset."		# preset.0, preset.1, etc...
const OPTIONS_SECTION_SUFFIX: String = ".options"	# preset.0.options, preset.1.options, etc...

# possible devices
const DEVICE_ANDROID: String = "Android"
const DEVICE_LINUX: String = "Linux"
const DEVICE_WINDOWS: String = "Windows"
const DEVICE_WEBGL: String = "WebGL"

# necessary options
const PLATFORM_KEY: String = "platform"
const ANDROID_FORMAT_KEY: String = "gradle_build/export_format"

# options to set
const EXPORT_PATH_KEY: String = "export_path" # for every device
const EMBED_PCK_KEY: String = "binary_format/embed_pck" # for linux and windows
const WEB_MOBILE_COMPRESSION_KEY: String = "vram_texture_compression/for_mobile" # for webgl


func _configure_all_presets() -> void:
	_configure_presets(PackedStringArray([
		DEVICE_ANDROID,
		DEVICE_LINUX,
		DEVICE_WINDOWS,
		DEVICE_WEBGL,
	]))


func _configure_android_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_ANDROID]))


func _configure_linux_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_LINUX]))


func _configure_windows_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_WINDOWS]))


func _configure_webgl_presets() -> void:
	_configure_presets(PackedStringArray([DEVICE_WEBGL]))



func _configure_presets(requested_devices: PackedStringArray) -> void:	
	# load export_presets.cfg file
	var config := ConfigFile.new()
	var load_error: Error = config.load(export_presets_path)
	if load_error == ERR_FILE_NOT_FOUND:
		_error_message("No export_presets.cfg found. Create the export presets first... [br]
			In the top bar: Project > Export > Add > select device... [br]
			If necessary: Editor > Manage export models > download necessary models... [br]
			What I download: Windows x86_64 (no console), Linux x86_64, Android (no source), Web no threads. Both debug and release")
		return
	if load_error != OK:
		_error_message("Cannot load export_presets.cfg: ", error_string(load_error))
		return

	var changed: bool = false
	var matched_devices := PackedStringArray()
	var preset_index: int = 0

	# cycle every preset (they are named preset.0, preset.1, etc...)
	while true:
		var preset_section: String = PRESET_SECTION_PREFIX + str(preset_index)
		if not config.has_section(preset_section):
			break

		# check if this is a requested device to edit
		var platform: String = str(config.get_value(preset_section, PLATFORM_KEY, ""))
		var device: String = _get_device_from_platform(platform)
		if requested_devices.has(device):
			matched_devices.append(device)
			# and try edit it
			changed = _configure_preset(config, preset_section, device) or changed

		preset_index += 1

	# warning for every device not found
	for device: String in requested_devices:
		if not matched_devices.has(device):
			_warning_message("No ", device, " export preset found")

	# if anything changed, other warning
	if not changed:
		_warning_message("Export presets are already configured")
		return

	# save file if edited
	_save_export_settings(config)


# configure single preset
# config is export_presets file, 
# preset_section is preset.0, preset.1, etc...
# device is Android, Linux, etc...
func _configure_preset(config: ConfigFile, preset_section: String, device: String) -> bool:
	# get options (they are named preset.0.options, preset.1.options, etc...)
	var options_section: String = preset_section + OPTIONS_SECTION_SUFFIX

	# get export path
	var export_path: String = _get_export_path(config, options_section, device)

	# create folders if not exist
	var export_directory: String = export_path.get_base_dir()
	var directory_error: Error = DirAccess.make_dir_recursive_absolute(export_directory)
	if directory_error != OK and directory_error != ERR_ALREADY_EXISTS:
		_error_message("Cannot create '", export_directory, "': ", error_string(directory_error))
		return false

	# and set export path
	var changed: bool = _set_value_if_different(config, preset_section, EXPORT_PATH_KEY, export_path)

	# and set specific device options
	match device:
		DEVICE_LINUX, DEVICE_WINDOWS:
			changed = _set_value_if_different(config, options_section, EMBED_PCK_KEY, true) or changed
		DEVICE_WEBGL:
			changed = _set_value_if_different(config, options_section, WEB_MOBILE_COMPRESSION_KEY, true) or changed

	return changed


func _get_device_from_platform(platform: String) -> String:
	# from options platform, return readable device
	match platform:
		"Android":
			return DEVICE_ANDROID
		"Linux", "Linux/BSD", "Linux/X11":
			return DEVICE_LINUX
		"Windows", "Windows Desktop":
			return DEVICE_WINDOWS
		"Web", "WebGL", "HTML5":
			return DEVICE_WEBGL
		_:
			return ""


# return path/to/Documents/Builds/device/project_name/file_name.extension
func _get_export_path(config: ConfigFile, options_section: String, device: String) -> String:
	# get project name (if some chars are invalid, they are replaced with underscore _)
	var project_name: String = str(ProjectSettings.get_setting("application/config/name", "GodotProject"))
	project_name = project_name.strip_edges().validate_filename()
	if project_name.is_empty():
		project_name = "GodotProject"

	# get "path/to/Documents/Builds/device/project_name" 
	# where device is Android, Linux, etc...
	if builds_root.is_empty():
		_reset_builds_root()
	var export_directory: String = builds_root.simplify_path().path_join(device).path_join(project_name)
	var file_name: String

	# get file_name.extension
	match device:
		DEVICE_ANDROID:
			var android_format: int = int(config.get_value(options_section, ANDROID_FORMAT_KEY, 0))
			file_name = project_name + (".aab" if android_format == 1 else ".apk")
		DEVICE_LINUX:
			file_name = project_name + ".x86_64"
		DEVICE_WINDOWS:
			file_name = project_name + ".exe"
		DEVICE_WEBGL:
			file_name = "index.html"
		_:
			file_name = project_name

	return export_directory.path_join(file_name)


func _set_value_if_different(config: ConfigFile, section: String, key: String, value: Variant) -> bool:
	# ignore if already correct
	if config.has_section_key(section, key) and config.get_value(section, key) == value:
		return false
	# or set it
	config.set_value(section, key, value)
	return true


#endregion


func _save_export_settings(config: ConfigFile) -> void:
	# save file if edited
	var save_error: Error = config.save(export_presets_path)
	if save_error == OK:
		_success_message("Export presets configured")
		push_warning("Export presets saved! Reload the project so the Export window refreshes its cached presets")
	else:
		_error_message("Cannot save export_presets.cfg: ", error_string(save_error))


func _save_project_settings(...success_message: Array) -> void:
	var save_error: Error = ProjectSettings.save()
	if save_error == OK:
		_success_message(success_message)
		push_warning("Project Settings saved! Reload the project to avoid cache bugs")
	else:
		_error_message("Cannot save Project Settings: ", error_string(save_error))


func _success_message(...message: Array) -> void:
	print("Quick Export Settings SUCCESS: ", message)


func _warning_message(...message: Array) -> void:
	push_warning("Quick Export Settings WARNING: ", message)


func _error_message(...message: Array) -> void:
	push_error("Quick Export Settings ERROR: ", message)
